### ISSUE TITLE
什么时候会执行动画呢？

### ISSUE THREAD

**Issue by Yixi** [ant-design/enter-animation#1]
是 change key？ 还是每次被调用render方法的时候都会执行动画？ 不太清楚机制，用起来有一些问题，总是在不应该触发动画的时候触发

**Comment by Yixi** [comment]
刚才看了下 好像是在 componentDidUpdate的时候会去触发动画，这样造成的问题是，我每次更新EnterAnimation里面的元素，都会导致动画触发。怎么避免这个问题呢，不能像CSSTransition Group那样做key判断吗

**Comment by jljsj33** [comment]
你好，0.9.0-beta9 已重构，，详细看 http://ant.design/components/enter-animation
