### ISSUE TITLE
Css.js 代码65行有个bug

### ISSUE THREAD

**Issue by pengxiaobao** [ant-design/enter-animation#4]
## Css.js 代码有个bug
- 在safari 5.17 浏览器上，会报异常
  <pre><code>
  removeStyle(m, style, oneBool) {
  //删除style;
  if (!m) {
    return false;
  }
  if (typeof style === 'object') {
    for (var _s in style) {
      m.style[_s] = '';
    }
  } else {
    var cArr = style.trim().split(';');
    cArr.map(function (arr) {
      if (arr && arr !== '') {
        var carr = m.style.cssText.split(';'),
          cOne = arr.split(':')[0].replace(/\s/g, ''),
          cTow = arr.split(':')[1] ? arr.split(':')[1].replace(/\s/g, '') : '';
        carr.map(function (_arr) {
          if (_arr && _arr !== '') {
            var tcOne = _arr.split(':')[0].replace(/\s/g, ''),
           <b style="color: red;font-size: 16px;">  tcTow = _arr.split(':')[1].replace(/\s/g, ''); </b>
            if (oneBool && tcOne.indexOf(cOne) >= 0) {
              m.style[arr.split(':')[0]] = '';
            } else if (tcOne.indexOf(cOne) >= 0 && tcTow === cTow) {
              m.style[arr.split(':')[0]] = '';
            }
          }
        });
      }
    });
  }
  </code></pre>

**Comment by afc163** [comment]
不要使用，马上会被替换。
